### PR TITLE
Explicit encoding

### LINKED ISSUE #89: UnicodeDecodeError: 'gbk' codec can't decode:
```
...
   change_request
  File "c:\path-to-project-folder\.venv\lib\site-packages\tbump\file_bumper.py", line 219, in compute_patches_for_change_request
    old_lines = file_path.read_text().splitlines(keepends=False)
File "C:\Python\Python37\lib\pathlib.py", line 1222, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 118: illegal multibyte sequence
```
A simple patch in file_bumper.py", line 219 fixes the problem:
`file_path.read_text()` -> `file_path.read_text("utf8")`

It would be nice if the next version adds this "utf8".

### PR DESCRIPTION
**Pull request by dmerejkowsky**
Fix #89

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
I've also added a `semgrep` rule so that we always specify specific encodings in the future

**Comment by cgestes** [comment]
The patch seems to override the encoding defined in the system to force utf-8.

Maybe I dont fully understand the situation but it looks like the bug this patch is supposed to fix is as follow: the system is configured with an encoding different than utf-8, the file being read is utf-8 (or not faulty using an utf8 encoding).

Are all the files processed by tbump utf-8?
If not I would rather allow overriding the default system encoding, but make it optional.

**Comment by cgestes** [comment]
Also a path to explore could be to work on raw content.
Is encoding needed?

**Comment by dmerejkowsky** [comment]
Meh. This was mostly an excuse to try out semgrep. And it works :)

I'm still not sure about the root cause of #89, so let's close this

**Pull request closed without merging**
