### PR TITLE
make file config entry optional

### PR DESCRIPTION
**Pull request by FlorianLudwig**
* allow empty `file` list
 * add default values for `message_template` and `tag_template`

### CODE REVIEW

**Comment by FlorianLudwig** [comment]
CI is failing due to PyPI being down :]

**Comment by dmerejkowsky** [comment]
I´m sorry, I´m afraid I can´t accept this PR.

### Using default values for git tag name ad commit message

tbump was specifically designed to have an *explicit* configuration. 

If you hard-code default values, here´s what´s going to happen

1/ People will fight for the "correct" default value

2/ Anyone who wants to change the default value would have to look up the documentation to find which key to *add*, which is time-consuming. It´s much simpler to open the config file and change the value if it´s already there.

### Allowing an empty file list

I´m really confused. What´s the use case for using tbump with an empty list of files to patch ?

**Comment by FlorianLudwig** [comment]
> 2/ Anyone who wants to change the default value would have to look up the documentation to find which key to add, which is time-consuming. It´s much simpler to open the config file and simply change the value if it´s already there.

I did not remove the config from `init` when it is generated, so it is not more time consuming.
What would probably cleaner thought, would have been to add them commented out

> I´m really confused. What´s the use case for using tbump with an empty list of files to patch ?

The pyproject.toml is always patched - i had no other file to patch in a project and tbump failed.

**Comment by dmerejkowsky** [comment]
> I did not remove the config from init when it is generated, so it is not more time consuming.

Still no. People remove commented code from config files, trust me one this :)

>  i had no other file to patch in a project and tbump failed.

Yeah., but that´s the bug in #93

**Comment by FlorianLudwig** [comment]
> Also, to re-iterate, if you are using tbump just to patch the version number in pyproject.toml, you may be using the wrong tool.
> Typically, using poetry version to bump the version of a project using poetry might be a better idea :)

This means I have to use different tools on different projects, wasn't that the idea of `tbump` to avoid?

But anyway, you are correct, if the other bug would be fixed it this wouldn't be needed.

**Pull request closed without merging**
